const P=s=>`<p>${s}</p>`,L=a=>`<ul>${a.map(x=>`<li>${x}</li>`).join('')}</ul>`,D=s=>`<pre>${s}</pre>`,
TB=r=>`<div class="sc"><table>${r.map((x,i)=>'<tr>'+x.map(c=>i?`<td class="l">${c}</td>`:`<th>${c}</th>`).join('')+'</tr>').join('')}</table></div>`;
const T=[['1. Introducción',[
['¿Qué es el soporte del sistema operativo?',P('El SO es el software fundamental que administra los recursos del computador y presta servicios a las aplicaciones: gestiona memoria, reparte el tiempo de CPU, se comunica con el hardware y se adapta a la virtualización, los contenedores y la nube.')+D('Usuario -> Aplicaciones -> Sistema Operativo -> Hardware')],
['Objetivos del sistema operativo',L(['Administrar los recursos del computador','Gestionar la memoria y administrar el procesador','Controlar los dispositivos de entrada y salida','Ser interfaz entre usuario y hardware','Ejecutar y controlar procesos','Garantizar seguridad y protección','Permitir que varias aplicaciones funcionen a la vez'])]]],
['2. Gestión de memoria',[
['¿Qué es y qué decide el SO?',P('Administra la RAM y la asigna a los procesos. Debe decidir: qué proceso recibe memoria, cuánta, dónde se coloca, cuándo se libera, qué hacer si la RAM no alcanza y cómo evitar que un proceso acceda a la memoria de otro.')+P('<b>Ejemplo:</b> Chrome, Word, Spotify y VS Code abiertos a la vez necesitan RAM; el SO reparte el espacio sin que interfieran.')],
['Memoria física y memoria virtual',P('<b>Física:</b> la RAM instalada (ej. 8 GB). <b>Virtual:</b> técnica que usa parte del almacenamiento secundario (SSD/HDD) como apoyo cuando la RAM no basta.')+P('⚠️ La memoria virtual es mucho más lenta que la RAM por la latencia del almacenamiento.')],
['Asignación de memoria',D('RAM\n+---------------------+\n| Sistema operativo   |\n+---------------------+\n| Proceso A           |\n+---------------------+\n| Proceso B           |\n+---------------------+\n| Proceso C           |\n+---------------------+\n| Espacio disponible  |\n+---------------------+')+P('Cuando un proceso termina, su espacio se libera para otro.')],
['Paginación',P('Divide la memoria virtual en <b>páginas</b> y la física en <b>marcos</b> del mismo tamaño. Las páginas no tienen que estar consecutivas en la RAM.')+D('Memoria virtual      RAM\n[Página 0] ------> [Marco 2]\n[Página 1] ------> [Marco 0]\n[Página 2] ------> [Marco 3]\n[Página 3] ------> [Marco 1]')+P('<b>Ventajas:</b> reduce la fragmentación externa, permite memoria virtual y facilita la administración.')],
['Segmentación',P('Divide la memoria según unidades lógicas del programa (código, datos, funciones, pila) y los segmentos pueden tener distinto tamaño.')+TB([['Paginación','Segmentación'],['Páginas de tamaño fijo','Segmentos lógicos'],['Se centra en la memoria física','Se relaciona con la estructura lógica'],['Páginas normalmente iguales','Segmentos de tamaños diferentes']])],
['Fragmentación',P('<b>Interna:</b> se asigna un bloque y queda espacio desperdiciado dentro de él.')+P('<b>Externa:</b> hay memoria libre en total, pero dividida en huecos pequeños y separados.')],
['Swapping',P('Mover temporalmente procesos (o partes) entre la RAM y el almacenamiento secundario (RAM -> Proceso -> SSD/HDD). Permite manejar una RAM limitada, aunque el acceso a disco es mucho más lento.')],
['Protección de memoria',P('El SO impide que un proceso modifique la memoria de otro. Mejora la <b>seguridad, estabilidad, aislamiento y confiabilidad</b>.')]]],
['3. Planificación (scheduling)',[
['¿Qué es y qué busca?',P('Es el mecanismo con el que el SO decide <b>qué proceso usa el CPU y por cuánto tiempo</b>. Con un solo núcleo y varios procesos (A, B, C, D) hay que elegir cuál va primero.')+L(['Aprovechar al máximo el CPU','Reducir tiempo de espera y de respuesta','Aumentar los procesos completados','Mantener el sistema equilibrado','Garantizar prioridad o equidad'])],
['Estados de un proceso',D('Nuevo -> Listo -> Ejecutando -> Terminado\n              ^        |\n              |        v\n              +---- Esperando (bloqueado)')+L(['<b>Nuevo:</b> se está creando','<b>Listo:</b> preparado para usar el CPU','<b>Ejecutando:</b> usa el CPU','<b>Bloqueado/esperando:</b> espera un recurso o evento','<b>Terminado:</b> finalizó'])],
['FCFS — First Come, First Served',P('El primero en llegar es el primero en ejecutarse: P1 → P2 → P3 → P4.')+P('<b>Ventaja:</b> sencillo. <b>Desventaja:</b> un proceso largo hace esperar mucho a los demás.')],
['SJF — Shortest Job First',P('Se ejecuta primero el de menor tiempo de CPU. Ej.: P1=8 ms, P2=3 ms, P3=5 ms → orden P2 → P3 → P1.')+P('<b>Ventaja:</b> puede reducir el tiempo promedio de espera. <b>Desventaja:</b> los procesos largos pueden esperar demasiado.')],
['Round Robin',P('Cada proceso recibe un tiempo limitado llamado <b>quantum</b>. Con quantum = 2 ms: P1 → P2 → P3 → P1 → P2 → P3. Es fundamental en sistemas interactivos.')+P('<b>Ventaja:</b> reparte el CPU entre procesos. <b>Desventaja:</b> si el quantum es muy pequeño, aumentan los cambios de contexto.')],
['Prioridades',P('Cada proceso tiene una prioridad (ej. 1 → P3, 2 → P1, 3 → P2) y el scheduler la usa para elegir.')+P('<b>Problema:</b> inanición (starvation), un proceso de baja prioridad espera demasiado. <b>Solución:</b> <i>aging</i>, subir gradualmente la prioridad de los que llevan mucho esperando.')],
['Cambio de contexto (context switch)',D('Proceso A -> guardar estado -> cambio de contexto -> cargar estado -> Proceso B')+P('El SO guarda registros, contador de programa y estado del proceso. Tiene un costo: durante el cambio no se hace trabajo útil del programa.')]]],
['4. Relación hardware-software',[
['Capas',D('      USUARIO\n         |\n   APLICACIONES\n         |\n  SISTEMA OPERATIVO (kernel)\n         |\n DRIVERS / CONTROLADORES\n         |\n     HARDWARE')],
['¿Qué hace el SO con cada componente?',TB([['Componente','Función del SO'],['CPU','Programa procesos, administra núcleos, gestiona interrupciones'],['RAM','Asigna y libera memoria, memoria virtual, protege espacios'],['Disco / SSD','Archivos, directorios, permisos, lectura y escritura'],['Teclado y mouse','Recibe las señales y las entrega a las aplicaciones'],['Tarjeta de red','Controla Ethernet, Wi-Fi, direcciones IP y comunicación']])],
['Drivers o controladores',P('Software que permite al SO comunicarse con un dispositivo específico. Sin el controlador adecuado, el SO puede no saber usar el dispositivo.')+D('Windows/Linux -> Driver de tarjeta gráfica -> GPU')],
['Interrupciones',P('Permiten que un dispositivo avise al procesador que necesita atención, sin revisar constantemente todos los dispositivos.')+D('Tecla -> Teclado -> Interrupción -> CPU -> SO -> Aplicación')],
['Llamadas al sistema (system calls)',P('Las aplicaciones no acceden directamente al hardware: piden servicios al SO.')+D('Word -> System Call -> Kernel -> Sistema de archivos -> Driver -> SSD')],
['Kernel',P('Núcleo del SO: gestiona procesos, memoria, CPU, dispositivos, seguridad, comunicación entre procesos y sistema de archivos.')+D('+---------------------+\n|    APLICACIONES     |\n+---------------------+\n|   SO  (KERNEL)      |\n+---------------------+\n|      HARDWARE       |\n+---------------------+')]]],
['5. Avances: virtualización, contenedores y cloud',[
['Virtualización',P('Permite crear una <b>máquina virtual (VM)</b> que funciona como un computador independiente dentro de uno físico. Una máquina puede ejecutar varios SO a la vez.')],
['Hipervisor',D('Hardware\n   |\nHipervisor\n   |\n[VM1 Linux] [VM2 Windows]')+L(['<b>Tipo 1:</b> corre directamente sobre el hardware (ej. KVM, Hyper-V)','<b>Tipo 2:</b> corre sobre un SO anfitrión (ej. VirtualBox)','Otros ejemplos: VMware'])],
['Ventajas y desventajas de la virtualización',P('<b>Ventajas:</b> aprovechar recursos, aislamiento, ejecutar distintos SO, entornos de prueba, administrar servidores, snapshots, menos hardware físico.')+P('<b>Desventajas:</b> consumo adicional, más complejidad, posible sobrecarga, el rendimiento depende del hardware.')],
['Contenedores',P('Comparten el kernel del SO anfitrión pero mantienen aisladas las aplicaciones y sus dependencias.')+D('Máquina física -> SO -> Motor de contenedores\n[App A+libs] [App B+libs] [App C+libs]')+TB([['Característica','Máquina virtual','Contenedor'],['Sistema operativo','Cada VM puede tener su SO','Comparte kernel'],['Aislamiento','Alto','Alto, pero diferente'],['Recursos','Mayor consumo','Generalmente menor'],['Inicio','Más lento','Generalmente más rápido'],['Tamaño','Mayor','Menor'],['Uso','Virtualización completa','Aplicaciones y servicios']])],
['Docker',P('Plataforma muy usada para contenedores. <b>Imagen:</b> plantilla con lo necesario. <b>Contenedor:</b> instancia en ejecución de una imagen. <b>Dockerfile:</b> archivo que define cómo construir la imagen.')+D('Imagen -> docker run -> Contenedor')],
['Kubernetes',P('Orquesta contenedores: con 100 contenedores, administrarlos a mano es complicado. Ayuda con despliegue, escalado, recuperación, balanceo y disponibilidad.')],
['Cloud OS',P('No es "un Windows en Internet": son sistemas y plataformas para proveer y administrar recursos computacionales en la nube.')+D('Usuario -> Internet -> Servicios Cloud\n-> VMs / Contenedores -> Servidores físicos\n-> Almacenamiento + Red + CPU')+P('<b>Características:</b> escalabilidad, virtualización, automatización, administración remota, alta disponibilidad, orquestación, servicios bajo demanda.')],
['IaaS, PaaS y SaaS',TB([['Modelo','Qué ofrece','Ejemplo'],['IaaS (Infraestructura)','Recursos de infraestructura','Máquinas virtuales, redes, almacenamiento'],['PaaS (Plataforma)','Plataforma para desarrollar y ejecutar apps','Entorno de despliegue de aplicaciones'],['SaaS (Software)','Aplicación usada por Internet','Correo o documentos en línea']])],
['Comparación general',TB([['Tecnología','Concepto principal','Ejemplo de uso'],['Virtualización','Crear máquinas virtuales','Servidor con varias VM'],['Contenedores','Aislar aplicaciones','Aplicaciones web'],['Kubernetes','Administrar contenedores','Grandes aplicaciones distribuidas'],['Cloud','Recursos bajo demanda','Servidores en la nube']])]]],
['6. Ejemplo integrador y repaso',[
['Aplicación web de una empresa',D('USUARIO -> INTERNET -> SERVIDOR\n  +-----------------------+\n  | Sistema operativo     |\n  | Kernel                |\n  | Contenedores          |\n  | App web + Base datos  |\n  +-----------------------+\n     CPU + RAM + SSD')+L(['Administra la RAM y planifica los procesos','Controla el CPU y se comunica con el hardware','Administra dispositivos y da seguridad','Permite ejecutar contenedores dentro de infraestructura virtualizada'])],
['Antes del examen recuerda',L(['<b>Gestión de memoria:</b> administra la RAM y la memoria virtual','<b>Scheduling:</b> decide qué proceso usa el CPU, cuándo y cuánto','<b>Kernel:</b> núcleo que administra los recursos fundamentales','<b>Driver:</b> permite al SO comunicarse con un dispositivo','<b>System call:</b> una aplicación pide un servicio al SO','<b>Virtualización:</b> ejecutar VM sobre un sistema físico','<b>Contenedor:</b> aísla una app compartiendo el kernel del anfitrión','<b>Cloud:</b> recursos informáticos bajo demanda por red'])]]]];
const GAL=[['componente-cpu','CPU'],['componente-ram','RAM'],['componente-disco','Disco / SSD'],['componente-teclado-mouse','Teclado y mouse'],['componente-red','Tarjeta de red']];
const gal=()=>'<div class="gal">'+GAL.map(g=>`<figure class="fig"><img src="images/${g[0]}.jpg" alt="${g[1]}" data-n="${g[0]}" data-t="0" loading="lazy"><figcaption>${g[1]}</figcaption></figure>`).join('')+'</div>';
const DENSE=['que-es-so','objetivos','gestion-memoria','fisica-virtual'];
let ci=0;const ph=n=>`<figure class="fig"><img src="images/${n}.jpg" alt="${n}" data-n="${n}" data-t="0" loading="lazy"></figure>`;
const item=(n,b)=>DENSE.includes(n)?ph(n)+b:`<div class="row"><div>${b}</div>${ph(n)}</div>`;
document.getElementById('guia-c').innerHTML=T.map((t,k)=>`<h3 class="tp">${t[0]}</h3>`+t[1].map((i,j)=>`<details${!k&&!j?' open':''}><summary>${i[0]}</summary><div>${IMG[ci]=='componentes'?(ci++,gal()+i[1]+(EXTRA[i[0]]||'')):item(IMG[ci++],i[1]+(EXTRA[i[0]]||''))}</div></details>`).join('')).join('');
const EX=['png','webp','jpeg'];
document.addEventListener('error',e=>{const m=e.target;if(m.tagName!='IMG'||!m.dataset.n)return;const t=+m.dataset.t;if(t<EX.length){m.dataset.t=t+1;m.src=`images/${m.dataset.n}.${EX[t]}`;return}
const f=m.closest('figure'),v=typeof VIS!='undefined'&&VIS[m.dataset.n];if(v){f.className='fig svg';f.innerHTML=v()}else{const r=f.parentElement;f.remove();if(r.classList.contains('row'))r.classList.add('solo')}},true);
const lb=document.createElement('div');lb.id='lb';lb.onclick=()=>lb.style.display='none';document.body.appendChild(lb);
document.addEventListener('click',e=>{if(e.target.matches('.fig img')){lb.innerHTML=`<img src="${e.target.src}">`;lb.style.display='flex'}});
const Q=[['¿Cuál es la función principal de la gestión de memoria?',['Administrar conexiones de Internet','Administrar y asignar memoria a los procesos','Crear usuarios','Administrar solo archivos'],1],
['¿Qué hace el scheduler?',['Administra el disco','Decide qué proceso utiliza el CPU','Instala drivers','Crea máquinas virtuales'],1],
['¿Qué es un driver?',['Un tipo de memoria','Un proceso','Software que permite comunicarse con hardware','Un algoritmo de planificación'],2],
['¿Qué diferencia fundamental hay entre una VM y un contenedor?',['La VM puede ejecutar su propio SO; el contenedor comparte el kernel del anfitrión','El contenedor trae su propio kernel; la VM comparte el del host','No hay diferencia','La VM no usa hipervisor'],0],
['¿Qué algoritmo utiliza un quantum?',['FCFS','SJF','Round Robin','Prioridades'],2],
['¿Qué problema puede producir la planificación por prioridades?',['Fragmentación externa','Inanición (starvation)','Fallos de driver','Swapping infinito'],1],
['¿Qué componente es el núcleo del sistema operativo?',['Driver','Kernel','Hipervisor','Scheduler'],1],
['¿Qué tecnología permite ejecutar varios SO virtuales en un mismo equipo físico?',['Paginación','Virtualización','Swapping','Segmentación'],1]];
function quiz(){let sc=0,n=0;const box=document.getElementById('quiz');box.innerHTML=Q.map((q,i)=>`<div class="card q"><b>${i+1}. ${q[0]}</b><div class="opts">${q[1].map((o,j)=>`<button data-i="${i}" data-j="${j}">${o}</button>`).join('')}</div></div>`).join('')+'<p class="res" id="q-r"></p><button class="btn o" id="q-re">Reiniciar</button>';
box.querySelectorAll('.opts').forEach((d,i)=>d.onclick=e=>{const b=e.target;if(b.tagName!='BUTTON'||d.dataset.done)return;d.dataset.done=1;const ok=+b.dataset.j==Q[i][2];b.classList.add(ok?'ok':'no');if(!ok)d.children[Q[i][2]].classList.add('ok');n++;sc+=ok;
document.getElementById('q-r').innerHTML=n<Q.length?`Llevas ${sc} correctas de ${n}.`:`<b>Resultado final: ${sc} / ${Q.length}</b>`});document.getElementById('q-re').onclick=quiz}
quiz();
const G=[['CPU','unidad central de procesamiento'],['RAM','memoria principal'],['Kernel','núcleo del sistema operativo'],['Proceso','programa en ejecución'],['Thread / Hilo','unidad de ejecución dentro de un proceso'],['Scheduler','planificador'],['Quantum','intervalo de CPU asignado a un proceso'],['Context switch','cambio de contexto'],['Driver','controlador de dispositivo'],['System call','llamada al sistema'],['Página','unidad de memoria virtual'],['Marco','unidad correspondiente en memoria física'],['Virtualización','creación de recursos virtuales'],['Máquina virtual','computador virtualizado'],['Contenedor','entorno aislado para una aplicación'],['Hipervisor','software que administra máquinas virtuales'],['Cloud computing','computación mediante recursos de nube'],['IaaS','infraestructura como servicio'],['PaaS','plataforma como servicio'],['SaaS','software como servicio']];
const gq=document.getElementById('g-q'),gr=()=>{const v=gq.value.toLowerCase();document.getElementById('g-l').innerHTML=G.filter(x=>(x[0]+x[1]).toLowerCase().includes(v)).map(x=>`<dt>${x[0]}</dt><dd>${x[1]}</dd>`).join('')||'<dd>Sin resultados</dd>'};gq.oninput=gr;gr();
